--INSERT INTO customer (id,address,balance,bedrooms,email,password,property_type,role) VALUES(1,'123 University Road',400,1,'gse@shangrila.gov.un',
--							   '$2a$10$8RJIMzuSclTsTbLTqWt42OmqPucA/P2ZDs3.jatwkMOlGFo2PqRfm',
--							   'flat','ROLE_ADMIN');